# What accumulated side effects may occur between naproxen, furosemide, and enalapril?

SELECT DISTINCT ?adeLabel (GROUP_CONCAT(DISTINCT ?drugLabel; SEPARATOR = ",") AS ?drugs)
       (COUNT(DISTINCT ?drug) AS ?nDrugs)

WHERE {
    VALUES ?drug { atc:M01AE02 atc:C03CA01 atc:C09AA02 } .
    ?drug dakikg:hasAdverseEvent ?ade .
    ?ade skos:prefLabel ?adeLabel .
    ?drug rdfs:label ?drugLabel .
    
    FILTER(LANGMATCHES(LANG(?adeLabel), "en")) .
    FILTER(LANGMATCHES(LANG(?drugLabel), "en"))
}

GROUP BY ?ade ?adeLabel
HAVING (COUNT(DISTINCT ?drug) > 1)