# Which drug-drug interactions are known for methotrexate (ATC L04AX03, L01BA01)?

SELECT DISTINCT ?ddiLabel 

WHERE {
   
  # select all DDIs involving methotrexate   
  VALUES ?drug {atc:L04AX03 atc:L01BA01}
    
  {<<?drug dakikg:hasInteractionWith ?anotherDrug>> dakikg:isMemberOfInteraction ?ddi .}
    UNION  
  {<<?anotherDrug dakikg:hasInteractionWith ?drug >> dakikg:isMemberOfInteraction ?ddi .} 

  ?ddi rdfs:label ?ddiLabel .
}